# Generated by Django 2.0 on 2018-01-14 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discography', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='performerband',
            unique_together={('performer', 'band', 'member')},
        ),
    ]
