# Generated by Django 2.0 on 2018-01-14 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discography', '0002_auto_20180115_0108'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='performerband',
            unique_together={('performer', 'member')},
        ),
    ]
