# Generated by Django 2.0 on 2018-01-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_auto_20180114_1908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RemoveField(
            model_name='tag',
            name='twit',
        ),
        migrations.AddField(
            model_name='twit',
            name='twit',
            field=models.ManyToManyField(to='twitter.Tag'),
        ),
    ]
