# Generated by Django 2.0 on 2018-01-14 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_auto_20180114_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twit',
            old_name='twit',
            new_name='tag',
        ),
    ]
