# Generated by Django 2.0 on 2018-01-20 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0007_auto_20180114_2018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'комментарий', 'verbose_name_plural': 'комментарии'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'тег', 'verbose_name_plural': 'теги'},
        ),
        migrations.AlterModelOptions(
            name='twit',
            options={'verbose_name': 'твит', 'verbose_name_plural': 'твиты'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
        migrations.AddField(
            model_name='comment',
            name='reply_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='twitter.Comment', verbose_name='ответ на'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter.User', verbose_name='автор'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=128, verbose_name='контент'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='dislikes',
            field=models.PositiveIntegerField(default=0, verbose_name='не нравится'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='нравится'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='published',
            field=models.DateTimeField(auto_now=True, verbose_name='дата публикации'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата обновления'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='twit',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter.User', verbose_name='автор'),
        ),
        migrations.AlterField(
            model_name='twit',
            name='content',
            field=models.TextField(verbose_name='контент'),
        ),
        migrations.AlterField(
            model_name='twit',
            name='dislikes',
            field=models.PositiveIntegerField(default=0, verbose_name='не нравится'),
        ),
        migrations.AlterField(
            model_name='twit',
            name='header',
            field=models.TextField(max_length=200, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='twit',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='нравится'),
        ),
        migrations.AlterField(
            model_name='twit',
            name='published',
            field=models.DateTimeField(auto_now=True, verbose_name='дата публикации'),
        ),
        migrations.AlterField(
            model_name='twit',
            name='updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата обновления'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=20, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=20, verbose_name='фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mid_name',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='второе имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nick_name',
            field=models.CharField(max_length=30, verbose_name='никнейм'),
        ),
    ]
