# Generated by Django 2.0 on 2018-01-21 00:23

import apps.shop.custom_checks
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'скидка', 'verbose_name_plural': 'скидки'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'группа товаров', 'verbose_name_plural': 'группы товаров'},
        ),
        migrations.AlterField(
            model_name='discount',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.Group', verbose_name='группа товаров'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='value',
            field=models.PositiveIntegerField(validators=[apps.shop.custom_checks.percentage], verbose_name='%'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=50, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name='есть в наличии'),
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Group', verbose_name='группа товаров'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='наименование'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(verbose_name='цена'),
        ),
    ]
